// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiixmzwmvxkjpyxyomth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppaXhtendtdnhranB5eHlvbXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODE4NjgsImV4cCI6MjA4NTM1Nzg2OH0.U5zH8ohdfocwQyIMlTE30HsBrJJXdx-jZc0V8IdtHxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});